[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.1.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.2.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[prune]
  go-tests = true
  unused-packages = true
